In [4]:
from getpass import getpass
import pandas as pd
import numpy as np
import re
import time

# Getting token

In [450]:
token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
token=re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]
token

'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQ4NTQxLCJ0aW1lc3RhbXAiOjE1ODk5MTU1MTEzNzAsImlhdCI6MTU4OTkxNTUxMSwiZXhwIjoxNTg5OTE5MTExfQ.UxMVVShu54sUbUN-KbWobuZwMelxeWYtste8FE4F2bE'

In [346]:
import requests

class BearerAuth(requests.auth.AuthBase):
    def __init__(self, token):
        self.token = token
    def __call__(self, r):
        r.headers["authorization"] = "Bearer " + self.token
        return r

# Artist's dataset

In [310]:
bb_artists = pd.read_csv('data/analysis/bb_artists_complete.csv').drop(columns='Unnamed: 0')
bb_artists.head()

,artist,uri,followers,genres,popularity,spotify_id
0,Doja Cat,spotify:artist:5cj0lLjcoR7YOSnhnX0Po5,1892264,"['la indie', 'pop']",91,5cj0lLjcoR7YOSnhnX0Po5
1,Megan Thee Stallion,spotify:artist:181bsRPaVXVlUKXrxwZfHK,1107542,"['houston rap', 'pop', 'pop rap', 'trap queen']",87,181bsRPaVXVlUKXrxwZfHK
2,The Weeknd,spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ,20303554,"['canadian contemporary r&b', 'canadian pop', ...",97,1Xyo4u8uXC1ZmMpatF05PJ
3,Drake,spotify:artist:3TVXtAsR1Inumwj472S9r4,46377628,"['canadian hip hop', 'canadian pop', 'hip hop'...",100,3TVXtAsR1Inumwj472S9r4
4,Roddy Ricch,spotify:artist:757aE44tKEUQEqRuT6GnEB,2526217,['melodic rap'],93,757aE44tKEUQEqRuT6GnEB

## Get Artists

Get an artists snapshot of sample artists based on a given metric. 

Given the metric filter and score range, get a list of artist ids and all relevant metrics for the given range of the respective metric. 

This endpoint is useful for artist profiling based on specific filters such as spotify performance, youtube performance and social media performance.

In [584]:
import time
token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
token = re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]

params_type = 'sp_followers'
df_total=pd.DataFrame()
i = 0

while i < 100000000:
    j = i
    params_list = [f'min={i}','max=100000000','offset=0']
    get_url = f'https://api.chartmetric.com/api/artist/{params_type}/list?{"&".join(params_list)}'
    
    try:
        response = requests.get(get_url, auth=BearerAuth(token))
        df = pd.DataFrame(response.json()['obj']['data'])
        df_total = df_total.append(df).reset_index(drop=True)
    except:
        print('except:', i) 
        token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
        token = re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]
        time.sleep(60)
        response = requests.get(get_url, auth=BearerAuth(token))
        print(response)
        df = pd.DataFrame(response.json()['obj']['data'])
        df_total = df_total.append(df).reset_index(drop=True)
    
    # reassigning i value to the last followers' value 
    i = df_total.loc[df_total.index[-1],'spotify_followers'] + 1

    # saving it as a csv. file
    df_total.to_csv('data/processed/chartmetric_0_5k.csv', index=False)
    
    # break the loop when it reaches the max. value of followers
    if i == j:
        break
    else:
        pass

try: 0
try: 1
try: 2
try: 3
try: 4
try: 5
try: 6
try: 7
try: 8
try: 9
try: 10
try: 11
try: 12
try: 13
try: 14
try: 15
try: 16
try: 17
try: 18
try: 19
except: 20
<Response [200]>
try: 21
try: 22
try: 23
try: 24
try: 25
try: 26
try: 27
try: 28
try: 29
try: 30
try: 31
try: 32
try: 33
try: 34
try: 35
try: 36
try: 37
try: 38
try: 39
except: 40
<Response [200]>
try: 41
try: 42
try: 43
try: 44
try: 45
try: 46
try: 47
try: 48
try: 49
try: 50
try: 51
try: 52
try: 53
try: 54
try: 55
try: 56
try: 57
try: 58
try: 59
except: 60
<Response [200]>
try: 61
try: 62
try: 63
try: 64
try: 65
try: 66
try: 67
try: 68
try: 69
try: 70
try: 71
try: 72
try: 73
try: 74
try: 75
try: 76
try: 77
try: 78
try: 79
except: 80
<Response [200]>
try: 81
try: 82
try: 83
try: 84
try: 85
try: 86
try: 87
try: 88
try: 89
try: 90
try: 91
try: 92
try: 93
try: 94
try: 95
try: 96
try: 97
try: 98
try: 99
except: 100
<Response [200]>
try: 101
try: 102
try: 103
try: 104
try: 105
try: 106
try: 107
try: 108
try: 109
try: 110
try: 111
try: 112
try: 113
try: 114
try: 115
try: 116
try: 117
try: 118
try: 119
except: 120
<Response [200]>
try: 121
try: 122
try: 123
try: 124
try: 125
try: 126
try: 127
try: 128
try: 129
try: 130
try: 131
try: 132
try: 133
try: 134
try: 135
try: 136
try: 137
try: 138
try: 139
except: 140
<Response [200]>
try: 141
try: 142
try: 143
try: 144
try: 145
try: 146
try: 147
try: 148
try: 149
try: 150
try: 151
try: 152
try: 153
try: 154
try: 155
try: 156
try: 157
try: 158
try: 159
except: 160
<Response [200]>
try: 161
try: 162
try: 163
try: 164
try: 165
try: 166
try: 167
try: 168
try: 169
try: 170
try: 171
try: 172
try: 173
try: 174
try: 175
try: 176
try: 177
try: 178
try: 179
except: 180
<Response [200]>
try: 181
try: 182
try: 183
try: 184
try: 185
try: 186
try: 187
try: 188
try: 189
try: 190
try: 191
try: 192
try: 193
try: 194
try: 195
try: 196
try: 197
try: 198
try: 199
except: 200
<Response [200]>
try: 201
try: 202
try: 203
try: 204
try: 205
try: 206
try: 207
try: 208
try: 209
try: 210
try: 211
try: 212
try: 213
try: 214
try: 215
try: 216
try: 217
try: 218
try: 219
except: 220
<Response [200]>
try: 221
try: 222
try: 223
try: 224
try: 225
try: 226
try: 227
try: 228
try: 229
try: 230
try: 231
try: 232
try: 233
try: 234
try: 235
try: 236
try: 237
try: 238
try: 239
try: 240
try: 241
try: 242
try: 243
try: 244
try: 245
try: 246
try: 247
try: 248
try: 249
try: 250
try: 251
try: 252
try: 253
try: 254
try: 255
except: 256
<Response [200]>
try: 257
try: 258
try: 259
try: 260
try: 261
try: 262
try: 263
try: 264
try: 265
try: 266
try: 267
try: 268
try: 269
try: 270
try: 271
try: 272
try: 273
try: 274
try: 275
except: 276
<Response [200]>
try: 277
try: 278
try: 279
try: 280
try: 281
try: 282
try: 283
try: 284
try: 285
try: 286
try: 287
try: 288
try: 289
try: 290
try: 291
try: 292
try: 293
try: 294
try: 295
except: 296
<Response [200]>
try: 297
try: 298
try: 299
try: 300
try: 301
try: 302
try: 303
try: 304
try: 305
try: 306
try: 307
try: 308
try: 309
try: 310
try: 311
try: 312
try: 313
try: 314
try: 315
except: 316
<Response [200]>
try: 317
try: 318
try: 319
try: 320
try: 321
try: 322
try: 323
try: 324
try: 325
try: 326
try: 327
try: 328
try: 329
try: 330
try: 331
try: 332
try: 333
try: 334
try: 335
except: 336
<Response [200]>
try: 337
try: 338
try: 339
try: 340
try: 341
try: 342
try: 343
try: 344
try: 345
try: 346
try: 347
try: 348
try: 349
try: 350
try: 351
try: 352
try: 353
try: 354
try: 355
except: 356
<Response [200]>
try: 357
try: 358
try: 359
try: 360
try: 361
try: 362
try: 363
try: 364
try: 365
try: 366
try: 367
try: 368
try: 369
try: 370
try: 371
try: 372
try: 373
try: 374
try: 375
except: 376
<Response [200]>
try: 377
try: 378
try: 379
try: 380
try: 381
try: 382
try: 383
try: 384
try: 385
try: 386
try: 387
try: 388
try: 389
try: 390
try: 391
try: 392
try: 393
try: 394
try: 395
except: 396
<Response [200]>
try: 397
try: 398
try: 399
try: 400
try: 401
try: 402
try: 403
try: 404
try: 405
try: 406
try: 407
try: 408
try: 409
try: 410
try: 411
try: 412
try: 413
try: 414
try: 415
except: 416
<Response [200]>
try: 417
try: 418
try: 419
try: 420
try: 421
try: 422
try: 423
try: 424
try: 425
try: 426
try: 427
try: 428
try: 429
try: 430
try: 431
try: 432
try: 433
try: 434
try: 435
except: 436
<Response [200]>
try: 437
try: 438
try: 439
try: 440
try: 441
try: 442
try: 443
try: 444
try: 445
try: 446
try: 447
try: 448
try: 449
try: 450
try: 451
try: 452
try: 453
try: 454
try: 455
except: 456
<Response [200]>
try: 457
try: 458
try: 459
try: 460
try: 461
try: 462
try: 463
try: 464
try: 465
try: 466
try: 467
try: 468
try: 469
try: 470
try: 471
try: 472
try: 473
try: 474
try: 475
except: 476
<Response [200]>
try: 477
try: 478
try: 479
try: 480
try: 481
try: 482
try: 483
try: 484
try: 485
try: 486
try: 487
try: 488
try: 489
try: 490
try: 491
try: 492
try: 493
try: 494
try: 495
except: 496
<Response [200]>
try: 497
try: 498
try: 499
try: 500
try: 501
try: 502
try: 503
try: 504
try: 505
try: 506
try: 507
try: 508
try: 509
try: 510
try: 511
try: 512
try: 513
try: 514
try: 515
except: 516
<Response [200]>
try: 517
try: 518
try: 519
try: 520
try: 521
try: 522
try: 523
try: 524
try: 525
try: 526
try: 527
try: 528
try: 529
try: 530
try: 531
try: 532
try: 533
try: 534
try: 535
except: 536
<Response [200]>
try: 537
try: 538
try: 539
try: 540
try: 541
try: 542
try: 543
try: 544
try: 545
try: 546
try: 547
try: 548
try: 549
try: 550
try: 551
try: 552
try: 553
try: 554
try: 555
except: 556
<Response [200]>
try: 557
try: 558
try: 559
try: 560
try: 561
try: 563
try: 564
try: 565
try: 566
try: 567
try: 568
try: 569
try: 570
try: 571
try: 572
try: 573
try: 574
try: 575
try: 576
except: 577
<Response [200]>
try: 578
try: 579
try: 580
try: 581
try: 582
try: 583
try: 584
try: 585
try: 586
try: 587
try: 589
try: 590
try: 591
try: 592
try: 593
try: 594
try: 595
try: 596
try: 597
except: 598
<Response [200]>
try: 599
try: 600
try: 601
try: 603
try: 604
try: 605
try: 606
try: 607
try: 608
try: 609
try: 610
try: 612
try: 613
try: 614
try: 615
try: 617
try: 619
try: 620
try: 621
except: 623
<Response [200]>
try: 625
try: 627
try: 629
try: 630
try: 631
try: 633
try: 635
try: 637
try: 638
try: 639
try: 641
try: 643
try: 644
try: 645
try: 647
try: 649
try: 650
try: 652
try: 653
except: 655
<Response [200]>
try: 657
try: 659
try: 661
try: 663
try: 665
try: 667
try: 669
try: 671
try: 673
try: 675
try: 677
try: 679
try: 681
try: 683
try: 685
try: 687
try: 689
try: 691
try: 693
except: 695
<Response [200]>
try: 697
try: 699
try: 701
try: 703
try: 705
try: 707
try: 709
try: 711
try: 713
try: 715
try: 717
try: 719
try: 721
try: 723
try: 725
try: 727
try: 729
try: 731
try: 733
except: 735
<Response [200]>
try: 737
try: 739
try: 741
try: 743
try: 745
try: 747
try: 749
try: 751
try: 753
try: 755
try: 757
try: 759
try: 761
try: 763
try: 765
try: 767
try: 769
try: 771
try: 773
except: 775
<Response [200]>
try: 777
try: 779
try: 781
try: 783
try: 785
try: 787
try: 789
try: 791
try: 793
try: 795
try: 797
try: 799
try: 801
try: 803
try: 805
try: 807
try: 809
try: 811
try: 813
except: 815
<Response [200]>
try: 817
try: 819
try: 821
try: 823
try: 825
try: 827
try: 829
try: 831
try: 833
try: 835
try: 837
try: 839
try: 841
try: 843
try: 845
try: 847
try: 849
try: 851
try: 853
except: 855
<Response [200]>
try: 857
try: 859
try: 861
try: 863
try: 865
try: 867
try: 869
try: 871
try: 873
try: 875
try: 877
try: 879
try: 881
try: 883
try: 885
try: 887
try: 889
try: 891
try: 893
except: 895
<Response [200]>
try: 897
try: 899
try: 901
try: 903
try: 905
try: 907
try: 909
try: 911
try: 913
try: 915
try: 917
try: 919
try: 921
try: 923
try: 925
try: 927
try: 929
try: 931
try: 933
except: 935
<Response [200]>
try: 937
try: 940
try: 942
try: 944
try: 946
try: 949
try: 951
try: 953
try: 955
try: 957
try: 959
try: 961
try: 963
try: 965
try: 968
try: 970
try: 973
try: 976
try: 978
except: 980
<Response [200]>
try: 982
try: 985
try: 987
try: 990
try: 992
try: 995
try: 998
try: 1000
try: 1003
try: 1006
try: 1009
try: 1012
try: 1015
try: 1018
try: 1020
try: 1023
try: 1026
try: 1028
try: 1030
except: 1032
<Response [200]>
try: 1035
try: 1038
try: 1040
try: 1042
try: 1045
try: 1047
try: 1050
try: 1053
try: 1056
try: 1058
try: 1061
try: 1064
try: 1066
try: 1069

try: 1071
try: 1073
try: 1076
try: 1078
try: 1080
except: 1083
<Response [200]>
try: 1085
try: 1088
try: 1091
try: 1093
try: 1096
try: 1098
try: 1101
try: 1104
try: 1107
try: 1110
try: 1113
try: 1116
try: 1119
try: 1122
try: 1125
try: 1128
try: 1131
try: 1134
try: 1137
except: 1140
<Response [200]>
try: 1143
try: 1146
try: 1149
try: 1152
try: 1155
try: 1158
try: 1161
try: 1164
try: 1167
try: 1170
try: 1173
try: 1176
try: 1179
try: 1182
try: 1185
try: 1188
try: 1191
try: 1194
try: 1197
except: 1200
<Response [200]>
try: 1203
try: 1206
try: 1209
try: 1212
try: 1215
try: 1218
try: 1221
try: 1225
try: 1228
try: 1231
try: 1234
try: 1237
try: 1240
try: 1243
try: 1246
try: 1249
try: 1252
try: 1255
try: 1258
except: 1261
<Response [200]>
try: 1264
try: 1267
try: 1271
try: 1274
try: 1277
try: 1280
try: 1283
try: 1286
try: 1289
try: 1292
try: 1295
try: 1299
try: 1303
try: 1306
try: 1310
try: 1314
try: 1318
try: 1321
try: 1324
except: 1327
<Response [200]>
try: 1331
try: 1335
try: 1339
try: 1342
try: 1346
try: 1349
try: 1353
try: 1357
try: 1361
try: 1365
try: 1368
try: 1372
try: 1376
try: 1380
try: 1384
try: 1388
try: 1392
try: 1395
try: 1399
except: 1403
<Response [200]>
try: 1407
try: 1411
try: 1415
try: 1419
try: 1423
try: 1427
try: 1431
try: 1435
try: 1439
try: 1443
try: 1447
try: 1451
try: 1455
try: 1459
try: 1463
try: 1467
try: 1471
try: 1475
try: 1479
except: 1483
<Response [200]>
try: 1487
try: 1492
try: 1497
try: 1501
try: 1503
try: 1505
try: 1507
try: 1509
try: 1511
try: 1513
try: 1515
try: 1517
try: 1520
try: 1523
try: 1526
try: 1529
try: 1532
try: 1535
try: 1538
except: 1541
<Response [200]>
try: 1544
try: 1547
try: 1551
try: 1554
try: 1557
try: 1560
try: 1564
try: 1567
try: 1571
try: 1575
try: 1578
try: 1581
try: 1585
try: 1589
try: 1593
try: 1597
try: 1601
try: 1605
try: 1609
except: 1613
<Response [200]>
try: 1617
try: 1622
try: 1626
try: 1630
try: 1634
try: 1638
try: 1642
try: 1646
try: 1650
try: 1654
try: 1659
try: 1663
try: 1667
try: 1671
try: 1675
try: 1679
try: 1684
try: 1688
try: 1692
except: 1696
<Response [200]>
try: 1700
try: 1704
try: 1711
try: 1720
try: 1730
try: 1738
try: 1746
try: 1754
try: 1762
try: 1770
try: 1777
try: 1784
try: 1790
try: 1796
try: 1803
try: 1810
try: 1816
try: 1823
try: 1830
except: 1836
<Response [200]>
try: 1843
try: 1849
try: 1855
try: 1861
try: 1868
try: 1874
try: 1881
try: 1887
try: 1893
try: 1899
try: 1905
try: 1911
try: 1916
try: 1922
try: 1928
try: 1935
try: 1941
try: 1946
try: 1953
except: 1960
<Response [200]>
try: 1967
try: 1973
try: 1980
try: 1986
try: 1993
try: 2000
try: 2006
try: 2013
try: 2019
try: 2026
try: 2032
try: 2038
try: 2044
try: 2051
try: 2057
try: 2063
try: 2069
try: 2076
try: 2082
except: 2088
<Response [200]>
try: 2095
try: 2103
try: 2110
try: 2117
try: 2124
try: 2131
try: 2138
try: 2145
try: 2152
try: 2159
try: 2166
try: 2173
try: 2180
try: 2188
try: 2195
try: 2202
try: 2210
try: 2218
try: 2225
except: 2231
<Response [200]>
try: 2238
try: 2245
try: 2252
try: 2259
try: 2266
try: 2273
try: 2280
try: 2287
try: 2295
try: 2302
try: 2310
try: 2317
try: 2325
try: 2333
try: 2341
try: 2348
try: 2355
try: 2363
try: 2371
try: 2379
try: 2387
try: 2395
try: 2403
try: 2411
try: 2420
try: 2428
try: 2436
except: 2444
<Response [200]>
try: 2453
try: 2460
try: 2468
try: 2476
try: 2484
try: 2493
try: 2502
try: 2511
try: 2519
try: 2527
try: 2534
try: 2543
try: 2551
try: 2560
try: 2569
try: 2577
try: 2586
try: 2594
try: 2602
except: 2611
<Response [200]>
try: 2620
try: 2629
try: 2637
try: 2646
try: 2654
try: 2665
try: 2674
try: 2683
try: 2692
try: 2700
try: 2709
try: 2718
try: 2728
try: 2739
try: 2749
try: 2758
try: 2768
try: 2777
try: 2786
try: 2796
try: 2806
try: 2816
try: 2825
try: 2836
try: 2846
try: 2856
try: 2866
try: 2877
try: 2891
try: 2902
try: 2913
try: 2922
try: 2932
try: 2942
try: 2952
try: 2962
try: 2972
except: 2983
<Response [200]>
try: 2993
try: 3001
try: 3003
try: 3005
try: 3008
try: 3011
try: 3014
try: 3018
try: 3023
try: 3028
try: 3034
try: 3041
try: 3050
try: 3058
try: 3068
try: 3078
try: 3087
try: 3100
try: 3114
except: 3128
<Response [200]>
try: 3150
try: 3169
try: 3189
try: 3208
try: 3225
try: 3243
try: 3258
try: 3273
try: 3289
try: 3305
try: 3319
try: 3335
try: 3349
try: 3363
try: 3378
try: 3393
try: 3408
try: 3422
try: 3437
except: 3451
<Response [200]>
try: 3467
try: 3481
try: 3495
try: 3510
try: 3524
try: 3539
try: 3552
try: 3566
try: 3580
try: 3595
try: 3608
try: 3623
try: 3637
try: 3654
try: 3668
try: 3684
try: 3699
try: 3715
try: 3731
try: 3748
try: 3765
try: 3781
try: 3794
try: 3809
try: 3824
try: 3838
except: 3854
<Response [200]>
try: 3870
try: 3886
try: 3901
try: 3917
try: 3933
try: 3950
try: 3967
try: 3985
try: 4003
try: 4018
try: 4035
try: 4052
try: 4069
try: 4086
try: 4104
try: 4120
try: 4137
try: 4155
try: 4172
try: 4192
try: 4211
try: 4229
try: 4248
try: 4268
except: 4285
<Response [200]>
try: 4304
try: 4324
try: 4343
try: 4362
try: 4381
try: 4399
try: 4418
try: 4436
try: 4456
try: 4475
try: 4496
try: 4515
try: 4533
try: 4553
try: 4574
try: 4594
try: 4615
try: 4638
try: 4660
try: 4680
try: 4700
try: 4724
try: 4745
try: 4770
try: 4791
try: 4813
try: 4834
try: 4855
try: 4878
try: 4903
try: 4926
try: 4949
try: 4970
try: 4990

In [600]:
df_total.head()

,chartmetric_artist_id,cpp_rank,spotify_popularity,spotify_followers,spotify_monthly_listeners,spotify_listeners_to_followers_ratio,facebook_likes,facebook_talks,youtube_channel_views,youtube_subscribers,wikipedia_views,soundcloud_followers
0,3647647,NaN,5,0,NaN,0.0,NaN,NaN,None,NaN,None,None
1,3647605,NaN,0,0,1.0,0.0,NaN,NaN,None,NaN,None,None
2,3647555,NaN,0,0,35.0,0.0,NaN,NaN,None,NaN,None,None
3,3647537,NaN,0,0,57.0,0.0,NaN,NaN,None,NaN,None,None
4,3647497,NaN,0,0,7.0,0.0,NaN,NaN,None,NaN,None,None

## Get Artist's ID

This API returns all the linked IDs. For example, you can retrieve chartmetric ID from Spotify, iTunes (Apple Music), or Deezer ID, and vice versa.

`type`: *chartmetric, spotify, itunes, deezer (string)*

`id`: *Specific Type ID (numeric)*

In [728]:
artists_df=pd.read_csv('data/processed/chartmetric_artists_complete.csv')
artists_df

,chartmetric_artist_id,cpp_rank,spotify_popularity,spotify_followers,spotify_monthly_listeners,spotify_listeners_to_followers_ratio,facebook_likes,facebook_talks,youtube_channel_views,youtube_subscribers,wikipedia_views,soundcloud_followers
0,3647647,NaN,5,0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
1,3647605,NaN,0,0,1.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
2,3647555,NaN,0,0,35.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
3,3647537,NaN,0,0,57.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
4,3647497,NaN,0,0,7.0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
295421,236,17.0,94,34674305,36407612.0,1.049988,86451915.0,94600.0,1.656572e+10,42600000.0,16159.0,844456.0
295422,2316,14.0,91,37155643,40017960.0,1.077036,79031680.0,401117.0,1.560374e+10,34300000.0,15716.0,1870697.0
295423,3963,5.0,93,45417613,46057393.0,1.014087,33030171.0,741174.0,1.542272e+10,41200000.0,17633.0,513092.0
295424,3380,1.0,100,46377628,61545223.0,1.327046,35057516.0,40283.0,7.575890e+09,21000000.0,467.0,2611028.0
295425,3648,6.0,93,63226094,53896619.0,0.852443,18341360.0,13069.0,2.051156e+10,44400000.0,9673.0,2300408.0

In [ ]:
df_total=pd.DataFrame()

for artist_id in artists_df.chartmetric_artist_id:
    get_url = f'https://api.chartmetric.com/api/artist/chartmetric/{artist_id}/get-ids'

    try:
        response = requests.get(get_url, auth=BearerAuth(token))
        df = pd.DataFrame(response.json()['obj'])
        df_total = df_total.append(df).reset_index(drop=True)
    except:
        print('except:', artist_id) 
        
        # refresh token
        token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
        token = re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]
        time.sleep(60)
        
        # request again
        response = requests.get(get_url, auth=BearerAuth(token))
        print(response)
        df = pd.DataFrame(response.json()['obj'])
        df_total = df_total.append(df).reset_index(drop=True)
    
    # saving it as a csv. file
    df_total.to_csv('data/processed/chartmetric_artists_ids.csv', index=False)

except: 3596566
<Response [200]>
except: 3596399
<Response [200]>
except: 3596051
<Response [200]>
except: 3595705
<Response [200]>
except: 3595583
<Response [200]>
except: 3594623
<Response [200]>
except: 3594497
<Response [200]>
except: 3594319
<Response [200]>
except: 3594212
<Response [200]>
except: 3689670
<Response [200]>
except: 3689314
<Response [200]>
except: 3688175
<Response [200]>
except: 3687499
<Response [200]>
except: 3684647
<Response [200]>
except: 3684417
<Response [200]>
except: 3684173
<Response [200]>
except: 3683962
<Response [200]>
except: 3683745
<Response [200]>
except: 3683487
<Response [200]>
except: 3689682
<Response [200]>
except: 3689400
<Response [200]>
except: 3688383
<Response [200]>
except: 3687861
<Response [200]>
except: 3686821
<Response [200]>
except: 3686088
<Response [200]>
except: 3685083
<Response [200]>
except: 3683942
<Response [200]>
except: 3683653
<Response [200]>
except: 3683351
<Response [200]>
except: 3689597
<Response [200]>
except: 3688168
<Response [200]>
except: 3687389
<Response [200]>
except: 3686059
<Response [200]>
except: 3685115
<Response [200]>
except: 3684541
<Response [200]>
except: 3682162
<Response [200]>
except: 3681695
<Response [200]>
except: 3681223
<Response [200]>
except: 3680917
<Response [200]>
except: 3689681
<Response [200]>
except: 3689275
<Response [200]>
except: 3687441
<Response [200]>
except: 3686548
<Response [200]>
except: 3685185
<Response [200]>
except: 3684768
<Response [200]>
except: 3684267
<Response [200]>
except: 3683888
<Response [200]>
except: 3683389
<Response [200]>
except: 3682844
<Response [200]>
except: 3689676
<Response [200]>
except: 3688063
<Response [200]>
except: 3680579
<Response [200]>
except: 3679703
<Response [200]>
except: 3679073
<Response [200]>
except: 3677259
<Response [200]>
except: 3676762
<Response [200]>
except: 3675792
<Response [200]>
except: 3674926
<Response [200]>
except: 3674151

## Artist - Fan Metrics


Get artist's fan metrics for various services. 

There are two ways to get fan metrics from each source: 

1. Return all fields (by default) 
2. Return only selected field (by adding 'field' parameter) 

For each source, here are the respective fields you can query for: 

SOURCE - VALID FIELDS 

spotify - followers, popularity, listeners 
deezer - fans 
facebook - likes 
twitter - followers 
youtube_channel - subscribers, views, comments, videos (this refers to the artist channel only) 
youtube_artist - views (this includes artist channel and all other videos featuring artist music) 
instagram - followers 
wikipedia - views 
bandsintown - followers 
soundcloud - followers 

If using the field parameter, ensure that the field is valid with respect to the source. 

For example, /wikipedia?field=views is valid, and /wikipedia?field=followers is invalid. 

Note that The API response may not return all the data points between the two dates, when we are missing the data. They may still show on our UI, since we are interpolating the missing data between the two existing data points. See the 'interpolated: true / false' in the response

`id`: chartmetric id

`source`: spotify, deezer, facebook, twitter, instagram, youtube_channel, youtube_artist, wikipedia, bandsintown, soundcloud

In [ ]:
get_url = f'https://api.chartmetric.com/api/artist/{id}/stat/{source}'

# Songs Datasets

## Get songs from charts

### SoundCloud

In [ ]:
# Requesting for date 20-04-01

In [692]:
token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
token = re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]

df_total=pd.DataFrame()
date = '2020-04-01'
genres = ['all-music', 'pop', 'hiphoprap', 'country', 'rock', 'jazzblues', 
         'classical', 'reggae', 'house', 'folksingersongwriter', 'techno', 'trance', 
         'disco', 'rbsoul', 'world', 'latin', 'piano', 'reggaeton', 'alternativerock', 
         'indie', 'triphop', 'electronic', 'deephouse', 'drumbass', 'dancehall', 
         'soundtrack', 'ambient', 'dubstep', 'danceedm', 'trap', 'metal']

for genre in genres:
    params_list =[f'date={date}','country_code=GLOBAL','kind=trending', f'genre={genre}']
    get_url = f'https://api.chartmetric.com/api/charts/soundcloud?{"&".join(params_list)}'

    try:
        response = requests.get(get_url, auth=BearerAuth(token))
        if response.json() != []:
            df = pd.DataFrame(response.json()['obj']['data'])
            df_total = df_total.append(df).reset_index(drop=True)
            print('try:', genre)
        else: 
            print('try:' genre)
            break
    except:
        print('except:', genre) 
        
        # refresh token
        token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
        token = re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]
        time.sleep(60)
        
        # request again
        response = requests.get(get_url, auth=BearerAuth(token))
        print(response)
        df = pd.DataFrame(response.json()['obj']['data'])
        df_total = df_total.append(df).reset_index(drop=True)
    
    # saving it as a csv. file
    df_total.to_csv('data/processed/chartmetric_soundcloud_full.csv', index=False)

try: all-music
try: pop
try: hiphoprap
try: country
try: rock
try: jazzblues
try: classical
try: reggae
try: house
try: folksingersongwriter
try: techno
try: trance
try: disco
try: rbsoul
try: world
try: latin
try: piano
try: reggaeton
try: alternativerock
try: indie
except: triphop
<Response [200]>
try: electronic
try: deephouse
try: drumbass
try: dancehall
try: soundtrack
try: ambient
try: dubstep
try: danceedm
try: trap
try: metal

In [694]:
df_total.shape

(6200, 31)

In [706]:
df_total.iloc[1,16]

'https://soundcloud.com/hichkasofficial/rosva'

## SEARCH

In [709]:
search_query='q=https://soundcloud.com/navmusic/turks-feat-travis-scott'
get_url = f'https://api.chartmetric.com/api/search?{search_query}'
response = requests.get(get_url, auth=BearerAuth(token))
response

In [710]:
response.json()

{'obj': {'artists': [],
  'playlists': {'spotify': [],
   'applemusic': [],
   'deezer': [{'id': '7437724424',
     'name': 'Turks (feat. Travis Scott, Gunna) - Nav',
     'image_url': 'https://api.deezer.com/playlist/7437724424/image',
     'owner_name': 'Vincenzo7107'}],
   'amazon': [],
   'youtube': []},
  'tracks': [],
  'curators': {'spotify': [], 'applemusic': [], 'deezer': []},
  'albums': [],
  'stations': [],
  'labels': [],
  'cities': []}}

## Get Track ID

In [711]:
track_id=7437724424
get_url = f'https://api.chartmetric.com/api/track/deezer/{track_id}/get-ids'
response = requests.get(get_url, auth=BearerAuth(token))
response

In [713]:
response.json()

{'obj': []}

## Track - Metadata

In [633]:
token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
token = re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]

In [635]:
track_id='786506983'
get_url = f'https://api.chartmetric.com/api/track/{track_id}'
response = requests.get(get_url, auth=BearerAuth(token))
response

In [ ]:

for track_id in df_total.id:
    get_url = f'https://api.chartmetric.com/api/track/{track_id}'

    try:
        response = requests.get(get_url, auth=BearerAuth(token))
        df = pd.DataFrame(response.json()['obj']['data'])
        df = df[['id', 'name', 'rank','genre', 'soundcloud_track_id', 'playcount_all', 'playcount_weekly','artist']]
        df_total = df_total.append(df).reset_index(drop=True)
    except:
        print('except:', genre) 
        
        # refresh token
        token_url = !curl -d '{"refreshtoken":"NivvXOOYbKUparpdKQFLdnTXv9d2yRqVEP6fDmILUPxd2yO82QGrUHEiZo75C4kq"}' -H "Content-Type: application/json" -X POST https://api.chartmetric.com/api/token
        token = re.findall(r'"([A-Za-z0-9._-]+)"',token_url[-1].split(',')[0])[1]
        time.sleep(60)
        
        # request again
        response = requests.get(get_url, auth=BearerAuth(token))
        print(response)
        df = df[['id', 'name', 'rank','genre', 'soundcloud_track_id', 'playcount_all', 'playcount_weekly','artist']]
        df_total = df_total.append(df).reset_index(drop=True)
    
    # saving it as a csv. file
    df_total.to_csv('data/processed/chartmetric_soundcloud.csv', index=False)