# EDA - Exploratory Data Analysis

HINT: 
- Faça uma pergunta para o DATA SET
- Limpe ao menos 3 colunas

In [22]:
import pandas as pd
import numpy as np

In [49]:
shark.loc[shark.loc[:,Sex  == 'lli',:]

AttributeError: 'DataFrame' object has no attribute 'Sex'

In [23]:
shark = pd.read_csv('GSAF5.csv',encoding='latin-1')
shark.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

# Verificar colunas 
- dropar colunas repetidas: Case number / href (links
- deletar coluna pdf

In [24]:
(~(shark['Case Number.1'] == shark['Case Number.2'])).sum()
(~(shark['Case Number.1'] == shark['Case Number'])).sum()
(~(shark['Case Number.2'] == shark['Case Number'])).sum()

2

In [25]:
# qual deletar?
mask1 = (~(shark['Case Number.1'] == shark['Case Number.2']))
mask2 = (~(shark['Case Number.1'] == shark['Case Number']))
mask3 = (~(shark['Case Number.2'] == shark['Case Number']))

#rows divergentes
div_cases = shark[['Case Number','Case Number.1','Case Number.2','pdf','Investigator or Source']].loc[(mask1|mask2|mask3),:]
div_cases.index

#Aqui decidimos que substituiriamos as strings conflitantes (divergentes), mas manteríamos apenas uma coluna "case number".
#Substituimos os valores corretos tirando os das coluna "pdf"

#We will use a variable to store temporary values of the DF: shark_temp
shark_temp = shark.copy()

shark_temp.iloc[list(div_cases.index),0] = shark.iloc[list(div_cases.index),16].apply(lambda x: x.split('-')[0])

#Agora, podemos dropar as colunas repetidas "Case Number.1" e "Case Number.2"
keep_cols = ['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'original order', 'Unnamed: 22','Unnamed: 23']

shark_temp = shark_temp.loc[:,keep_cols]

## Removendo "Href" ou "href formula"

## Limpando colunas com mts NaN

In [26]:
shark_temp.isna().sum()/shark_temp.shape[0]*100

Case Number                0.000000
Date                       0.000000
Year                       0.000000
Type                       0.000000
Country                    0.717623
Area                       6.708945
Location                   8.277704
Activity                   8.795060
Name                       3.337784
Sex                        9.462617
Age                       44.742991
Injury                     0.450601
Fatal (Y/N)                0.317089
Time                      53.621495
Species                   48.965287
Investigator or Source     0.250334
pdf                        0.000000
href formula               0.016689
href                       0.050067
original order             0.000000
Unnamed: 22               99.983311
Unnamed: 23               99.966622
dtype: float64

In [27]:
print(shark_temp.loc[:,'Unnamed: 22'].unique())
print(shark_temp.loc[:,'Unnamed: 23'].unique())

#since those two last columns have no meaningfull information, we will discard them.

#Column "original order" has unique numbers ranging from 1 to 5993, which is like an index, but in case timer order. 
shark_temp = shark_temp.loc[:,'Case Number':'href']
shark_temp

[nan 'stopped here']
[nan 'Teramo' 'change filename']

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,NaN,Struck by fin on chest & leg,N,NaN,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4,2016.09.16,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,NaN,No injury: Knocked off board by shark,N,NaN,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,ND.0005,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5988,ND.0004,Before 1903,0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5989,ND.0003,1900-1905,0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5991,ND.0001,1845-1853,0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

## removing other futile columns

In [28]:
# name
# Investigator or Source
# Location : 3930 unique values... from 5992. It would be really hard to find all typos of same areas.
keep_cols = ['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Activity', 'Sex ', 'Age', 
             'Injury', 'Fatal (Y/N)', 'Time', 'Species ', 'pdf', 'href formula', 'href']
shark_temp = shark_temp.loc[:,keep_cols]

In [29]:
#cleaning column names:
col_list = [i.lower().strip().replace(' ', '_') for i in shark_temp.columns]
shark_temp.columns = col_list

## Transforming Fatal(Y/N)

In [30]:
shark_temp['fatal'] = shark_temp.loc[:,'fatal_(y/n)'].apply(lambda x: 1 if x == 'Y' else 0)

In [31]:
#changing columns
keep_cols = ['case_number', 'date', 'year', 'type', 'country', 'area', 'activity',
       'sex', 'age', 'injury', 'fatal', 'time', 'species', 'pdf',
       'href_formula', 'href']
shark_temp = shark_temp.loc[:,keep_cols]

In [32]:
shark_temp.type.value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Sea Disaster     220
Boat             200
Boating          110
Name: type, dtype: int64

In [47]:
shark_temp.groupby(['country','type'])['fatal'].describe().sort_values(by=['count'], ascending=False).loc[['USA','AUSTRALIA','BRAZIL']]

                         count      mean       std  min  25%  50%   75%  max
country   type
USA       Unprovoked    1646.0  0.089307  0.285274  0.0  0.0  0.0  0.00  1.0
AUSTRALIA Unprovoked     897.0  0.290970  0.454463  0.0  0.0  0.0  1.00  1.0
USA       Provoked       204.0  0.019608  0.138989  0.0  0.0  0.0  0.00  1.0
          Invalid        183.0  0.426230  0.495885  0.0  0.0  0.0  1.00  1.0
AUSTRALIA Provoked       130.0  0.015385  0.123553  0.0  0.0  0.0  0.00  1.0
          Invalid        113.0  0.530973  0.501263  0.0  0.0  1.0  1.00  1.0
BRAZIL    Unprovoked      86.0  0.348837  0.479398  0.0  0.0  0.0  1.00  1.0
AUSTRALIA Boat            64.0  0.000000  0.000000  0.0  0.0  0.0  0.00  0.0
          Boating         51.0  0.039216  0.196039  0.0  0.0  0.0  0.00  1.0
USA       Boat            38.0  0.000000  0.000000  0.0  0.0  0.0  0.00  0.0
          Sea Disaster    29.0  0.586207  0.501230  0.0  0.0  1.0  1.00  1.0
AUSTRALIA Sea Disaster    24.0  0.666667  0.481543  0.0  0.0  1.0  1.00  1.0
USA       Boating         16.0  0.000000  0.000000  0.0  0.0  0.0  0.00  0.0
BRAZIL    Invalid          8.0  0.625000  0.517549  0.0  0.0  1.0  1.00  1.0
          Provoked         4.0  0.250000  0.500000  0.0  0.0  0.0  0.25  1.0
          Sea Disaster     4.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0

In [16]:
shark_temp_1.groupby(['type'])['fatal'].describe().sort_values(by=['mean'], ascending=False).head(10)

               count      mean       std  min  25%  50%  75%  max
type
Sea Disaster   214.0  0.700935  0.458922  0.0  0.0  1.0  1.0  1.0
Invalid        517.0  0.470019  0.499584  0.0  0.0  0.0  1.0  1.0
Unprovoked    4279.0  0.251227  0.433769  0.0  0.0  0.0  1.0  1.0
Boating        110.0  0.072727  0.260877  0.0  0.0  0.0  0.0  1.0
Provoked       550.0  0.029091  0.168214  0.0  0.0  0.0  0.0  1.0
Boat           198.0  0.015152  0.122465  0.0  0.0  0.0  0.0  1.0

In [17]:
shark_temp.activity == "Spear fishing"

0       False
1       False
2       False
3       False
4       False
        ...
5987    False
5988    False
5989    False
5990    False
5991    False
Name: activity, Length: 5992, dtype: bool

In [18]:
shark_temp.loc[shark_temp.activity == "Spearfishing",:]

,case_number,date,year,type,country,area,activity,sex,age,injury,fatal,time,species,pdf,href_formula,href
12,2016.09.01,01-Sep-16,2016,Unprovoked,USA,California,Spearfishing,M,22,Two toes broken & lacerated,0,NaN,White shark,2016.09.01-McQuillen.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
27,2016.07.23.a,23-Jul-16,2016,Unprovoked,BAHAMAS,Abaco Islands,Spearfishing,M,NaN,Lacerations to face and right leg,0,NaN,"Bull shark, 6'",2016.07.23.a-Cutbirth.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
43,2016.06.23,23-Jun-16,2016,Unprovoked,SOUTH AFRICA,Western Cape Province,Spearfishing,M,43,Injuries to left leg & right hand,0,NaN,White shark,2016.06.23-Rysport.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
47,2016.06.15.a,15-Jun-16,2016,Provoked,AUSTRALIA,Western Australia,Spearfishing,M,19,No injury but shark punctured his wetsuit afte...,0,NaN,5' shark,2016.06.15.a-Vale.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
54,2016.06.02.b,02-Jun-16,2016,Unprovoked,AUSTRALIA,New South Wales,Spearfishing,M,NaN,"No injury, but sharks repeatedly hit their fin...",0,NaN,Bronze whaler sharks x 3,2016.06.02.b-Matigan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4299,1949.00.00.c,1949,1949,Unprovoked,PAPUA NEW GUINEA,Bougainville (North Solomons),Spearfishing,M,18,"FATAL, ""Nearly bitten in two through loin"".",1,NaN,NaN,1949.00.00.c-Orava.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4324,1948.03.00,Mar-48,1948,Provoked,PAPUA NEW GUINEA,"New Ireland Province, Bismarck Archipelago",Spearfishing,M,30,Leg bitten by shark that he had speared PROVO...,0,NaN,"""grey shark""",1948.03.00-Reiman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4330,1948.00.00.b,1948,1948,Provoked,PAPUA NEW GUINEA,Bougainville (North Solomons),Spearfishing,M,NaN,Bitten on face while taking shark off spear PR...,0,NaN,NaN,1948.00.00.b-TungIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4460,1943.00.00.c,Fall 1943,1943,Unprovoked,USA,Hawaii,Spearfishing,M,NaN,Calf nipped in each case,0,NaN,"""small sharks""",1943.00.00.c - Midway.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
4461,1943.00.00.b,Fall 1943,1943,Unprovoked,USA,Hawaii,Spearfishing,M,NaN,Calf nipped in each case,0,NaN,"""small sharks""",1943.00.00.b - Midway.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [19]:
shark_temp.loc[shark_temp.type == 'Invalid',:]

,case_number,date,year,type,country,area,activity,sex,age,injury,fatal,time,species,pdf,href_formula,href
50,2016.06.07,07-Jun-16,2016,Invalid,USA,South Carolina,Surfing,M,27,"No injury, board damaged",0,11h30,Said to involve an 8' shark but more likely da...,2016.06.07-Oneill.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
73,2016.04.08,08-Apr-16,2016,Invalid,CAPE VERDE,Boa Vista Island,NaN,M,60,"""Serious""",0,NaN,Shark involvement not confirmed,2016.04.08-CapeVerde.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
75,2016.04.07.a,07-Apr-16,2016,Invalid,USA,Florida,SUP,M,NaN,Fell off board when spinner shark leapt from t...,0,NaN,NaN,2016.04.07.a-Trinidad.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
81,2016.03.13,13-Mar-16,2016,Invalid,USA,California,Surfing,NaN,NaN,Board reportedly bumped by shark. No injury,0,Morning,Shark involvement not confirmed,2016.03.13-BolsaChicaSurfer.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
90,2016.02.10.R,Reported 10-Feb-2016,2016,Invalid,CAYMAN ISLANDS,Grand Cayman,Feeding stingrays?,M,65,Minor injury to wrist from Southern stingray,0,NaN,No shark involvement,2016.02.10.R-Branson-stingray.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5841,1767.00.00,1767,1767,Invalid,FRANCE,Côte d'Azur,Bathing,M,NaN,Lacerations to arm & leg,0,NaN,Description of shark does not ring true,1767.00.00-Matthews.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5849,1733.00.00,1733,1733,Invalid,ICELAND,Bardestrand,NaN,NaN,NaN,"Partial hominid remains recovered from shark, ...",0,NaN,NaN,1733.00.00-Iceland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5855,1642.00.00.b,Late 1600s Reported 1728,1642,Invalid,GUINEA,NaN,Went overboard,M,NaN,FATAL,1,NaN,NaN,1642.00.00.b-Nieuwstadt.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5917,ND.0086,"No date, Before 1975",0,Invalid,PAPUA NEW GUINEA,Milne Bay Province,Scuba diving,M,NaN,Said to be fatal but incident highly questionable,1,NaN,"Tiger shark, 4.6 m to 6 m [15' to 20']",ND-0086-DanHogan.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5922,ND.0081,"No date, Before 1963",0,Invalid,USA,Hawaii,Diving,M,NaN,A 4.3 m [14'] shark made threat display. No in...,0,NaN,NaN,ND-0081-Valentine.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [37]:
#quando na coluna type, tiver 'invalid', 
#checar activity:
 #   se contiver alguma das palavras da lista, 
  #  substituir invalid por 'unprovoked'


#shark_temp.activity.loc[mask,:]

In [38]:
shark_temp.loc[shark_temp.activity.isna(),:]

,case_number,date,year,type,country,area,activity,sex,age,injury,fatal,time,species,pdf,href_formula,href
31,2016.07.16.a,16-Jul-16,2016,Unprovoked,USA,Florida,NaN,F,11,Minor injury to toes,0,11h00,NaN,2016.07.16.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
40,2016.06.27,27-Jun-16,2016,Unprovoked,USA,South Carolina,NaN,M,35,Minor injury,0,16h20,3' to 4' shark,2016.06.27-Sullivans.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
73,2016.04.08,08-Apr-16,2016,Invalid,CAPE VERDE,Boa Vista Island,NaN,M,60,"""Serious""",0,NaN,Shark involvement not confirmed,2016.04.08-CapeVerde.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
78,2016.03.28.b,28-Mar-16,2016,Unprovoked,USA,Florida,NaN,M,Teen,Minor injury to arm. Possibly caused by smalll...,0,NaN,Shark involvement not confirmed,2016.03.28.b-Kawa.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
80,2016.03.26,26-Mar-16,2016,Provoked,BAHAMAS,NaN,NaN,M,9,Minor injury to chest PROVOKED INCIDENT,0,NaN,"Nurse shark, 2.5-ft",2016.03.26-Kreckman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5959,ND.0034,1940-1946,0,Sea Disaster,PACIFIC OCEAN,NaN,NaN,M,NaN,FATAL,1,NaN,NaN,ND-0034-8-men-on-raft.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5967,ND.0025,Before 1927,0,Unprovoked,AUSTRALIA,New South Wales,NaN,M,NaN,NaN,0,NaN,NaN,ND-0025-Sgt-SpectacleIsland.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5972,ND.0020,1920 -1923,0,Unprovoked,AUSTRALIA,Queensland,NaN,M,NaN,FATAL,1,NaN,NaN,ND-0020-3JapaneseDivers.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5982,ND.0010,Circa 1862,0,Unprovoked,USA,Hawaii,NaN,F,NaN,Ankle bitten,0,NaN,NaN,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...
5990,ND.0002,1883-1889,0,Unprovoked,PANAMA,NaN,NaN,M,NaN,FATAL,1,NaN,NaN,ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...

In [39]:
shark_act = shark_temp.loc[shark_temp.type == 'Invalid',:].loc[:,'activity']
shark_act

50                 Surfing
73                     NaN
75                     SUP
81                 Surfing
90      Feeding stingrays?
               ...
5841               Bathing
5849                   NaN
5855        Went overboard
5917          Scuba diving
5922                Diving
Name: activity, Length: 519, dtype: object

In [40]:
list_unprovoked_activities = ['[Ss]urf\w+','[Ss]wim\w+','[Bb]ath\w+', '[Ww]ad\w+','[Bb]oard\w+','[Ss]norkel\w+', '[Kk]ayak\w+','[Dd]iv\w+']

In [41]:
def func_re (x):
    y = 'Invalid'
    for activity in list_unprovoked_activities:
        try:
            if len(re.findall(activity, x)) != 0:
                y = 'Unprovoked'
                break
        except:
            break
    return y

In [42]:
shark_temp.loc[shark_temp.type == 'Invalid',['type']]

         type
50    Invalid
73    Invalid
75    Invalid
81    Invalid
90    Invalid
...       ...
5841  Invalid
5849  Invalid
5855  Invalid
5917  Invalid
5922  Invalid

[519 rows x 1 columns]

In [43]:
shark_temp.loc[shark_temp.type == 'Invalid',['type']] = shark_act.apply(lambda x: func_re(x))

In [44]:
shark_temp.type.value_counts()

Unprovoked      4386
Provoked         557
Invalid          519
Sea Disaster     220
Boat             200
Boating          110
Name: type, dtype: int64

In [ ]:
shark_act

In [ ]:
import re

In [ ]:
shark_temp.loc[0,'activity']

In [ ]:
re.findall('[Ss]urf\w+', 'board Surfing b')

In [ ]:
print(list(shark_temp.activity.unique()))

## Types

# Limpar 3 colunas

## Limpar a coluna 'Date'
 - se male == unknown

In [ ]:
import re

In [ ]:
shark_temp['year_year'] =

In [ ]:
def year_year
    if len(re.findall(pattern,text)) == 1 :
        shark_temp['year_year'] = re.findall(pattern,text)
    elif len(re.findall(pattern,text)) == 2 :
        shark_temp['year_year'] = (int(re.findall(pattern,text)[0])+int(re.findall(pattern,text)[1]))/2
    else:
        return x

In [ ]:
shark_temp['date'].apply(lambda x: x+x)



## Limpar a coluna 'Type'

## Limpar a coluna Year 
criar nova agrupando por décadas

# A sua chance de morrer por um ataque de tubarão é maior se você provocar um tubarão?

## Criar coluna de número de sobreviventes em um ataque

## Coluna com flags de: injuries / not